" MLN setup for vim
" created 2/20/2015
"
" run pathogen to handle all bundle plubins
call pathogen#infect()
call pathogen#helptags()
"
" enable completion on certain files
augroup loadgroup
   autocmd!
   autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
   autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim
   "
   " Other filetypes where we want spaces instead of tabs
   autocmd Filetype tex,bib,text,cov,mail,html,rst set expandtab
   autocmd Filetype rst set shiftwidth=4
   autocmd Filetype markdown set expandtab
   autocmd Filetype markdown set shiftwidth=2
   autocmd Filetype markdown set tw=80
   autocmd Filetype yaml set expandtab
   autocmd Filetype yaml set shiftwidth=2
   autocmd Filetype mako set expandtab
   autocmd Filetype mako set shiftwidth=2
augroup END
"
" solorize color schemeing
syntax on
filetype plugin indent on
set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized
"
" vim-go
let g:go_fmt_command = "goimports"
let g:go_auto_type_info = 1
"
" If you want to disable gofmt on save
" let g:go_fmt_autosave = 0
"
" NERDTREE
":noremap <C-g> :NERDTreeToggle<CR>
" Status line types/signatures.
let g:go_auto_type_info = 1
"
" allow backspace to delete
set backspace=indent,eol,start
" indent  allow backspacing over autoindent
" eol     allow backspacing over line breaks (join lines)
" start   allow backspacing over the start of insert; CTRL-W and CTRL-U
"        stop once at the start of insert.
"
set nocompatible
set viminfo='1,/10,:10,h
